A title cell with a table of all dataset issues and fixes

#Task 1 — Clean the Data

In [13]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder , MinMaxScaler, StandardScaler

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    6 non-null      int64
 1   age            3 non-null      float64
 2   city           4 non-null      str
 3   gender         6 non-null      str
 4   annual_income  6 non-null      int64
dtypes: float64(1), int64(2), str(2)
memory usage: 372.0 bytes

In [15]:
df.describe()

       customer_id        age  annual_income
count     6.000000   3.000000       6.000000
mean      2.833333  33.333333   79166.666667
std       1.471960   7.637626   27643.564652
min       1.000000  25.000000   40000.000000
25%       2.000000  30.000000   65000.000000
50%       2.500000  35.000000   80000.000000
75%       3.750000  37.500000   91250.000000
max       5.000000  40.000000  120000.000000

Impute missing values in age with the median and in city with the mode

In [16]:
df['age'].fillna(df['age'].median() )

0    25.0
1    35.0
2    35.0
3    35.0
4    35.0
5    40.0
Name: age, dtype: float64

In [17]:
df['city'].fillna(df['city'].mode()[0])

0    Mumbai
1     Delhi
2     Delhi
3    Mumbai
4     Delhi
5     Delhi
Name: city, dtype: str

# Remove duplicate rows

In [18]:
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            5  40.0     NaN    Male          95000

#Task 2 — Encode Categorical Columns
After cleaning, encode the categorical columns:

Apply One-Hot Encoding to city

In [19]:
df = pd.get_dummies(df, columns=['city'],prefix='city' )

Apply Label Encoding to gender

In [20]:
l_e= LabelEncoder()
df['gender'] = l_e.fit_transform(df['gender'])

In [21]:
print(df)

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       1          40000       False         True
1            2   NaN       0          80000        True        False
2            3  35.0       0          60000       False        False
3            4   NaN       1         120000       False         True
4            5  40.0       1          95000       False        False

#Task 3 — Scale Numerical Features
Scale age and annual_income using both methods below on the cleaned dataFrame, and print the results of each:

In [23]:
features = [ 'age','annual_income']

#Min-Max Scaling (using MinMaxScaler)

In [26]:

min_max= MinMaxScaler()
df_Min_Max= df.copy()
df_Min_Max[features]=min_max.fit_transform(df[features])
print("Min_Max_Scaler :\n", df_Min_Max[features])

Min_Max_Scaler :
         age  annual_income
0  0.000000         0.0000
1       NaN         0.5000
2  0.666667         0.2500
3       NaN         1.0000
4  1.000000         0.6875

# Standardisation  (using StandardScaler)

In [28]:
Standard=StandardScaler()
df_standard=df.copy()
df_standard[features]=Standard.fit_transform(df_standard[features])
print("\nStandradised :\n" , df_standard[features])

Standradised :
         age  annual_income
0 -1.336306      -1.410970
1       NaN       0.036179
2  0.267261      -0.687396
3       NaN       1.483328
4  1.069045       0.578860